apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaz

resources:
  - ../../../base
  - ../../../apps/gaz

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      env: dev
      policy-tier: application
