apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http-ingress
  namespace: cv
spec:
  podSelector:
    matchLabels:
      app: cv-website
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
