apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: forgejo-default-deny-egress
  namespace: forgejo
spec:
  podSelector:
    matchLabels:
      app: forgejo
  policyTypes:
  - Egress
