apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: network-policies
    app.kubernetes.io/part-of: network-policies
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pascariucosmin93/k8s-network-policies.git
        revision: HEAD
        directories:
          - path: network-policies/envs/dev/*
          - path: network-policies/envs/prod/*
  template:
    metadata:
      name: 'netpol-{{ index .path.segments 2 }}-{{ index .path.segments 3 }}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      labels:
        app.kubernetes.io/part-of: network-policies
        app.kubernetes.io/name: 'netpol-{{ index .path.segments 2 }}-{{ index .path.segments 3 }}'
        env: '{{ index .path.segments 2 }}'
        namespace: '{{ index .path.segments 3 }}-{{ index .path.segments 2 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/pascariucosmin93/k8s-network-policies.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 3 }}-{{ index .path.segments 2 }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - ServerSideApply=true
