apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-namespace
  labels:
    app.kubernetes.io/name: allow-internal-namespace
    app.kubernetes.io/part-of: network-policies
    app.kubernetes.io/component: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
