apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns
  labels:
    app.kubernetes.io/name: allow-dns
    app.kubernetes.io/part-of: network-policies
    app.kubernetes.io/component: baseline
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchExpressions:
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values:
                - kube-system
            - key: k8s:k8s-app
              operator: In
              values:
                - kube-dns
                - coredns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*.svc.cluster.local"
              - matchPattern: "*.cluster.local"
              - matchPattern: "*.svc"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:app.kubernetes.io/name: coredns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*.svc.cluster.local"
              - matchPattern: "*.cluster.local"
              - matchPattern: "*.svc"
