apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-ingress
  namespace: jobs-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: jobs-platform
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jobs-platform
    ports:
    - port: 8080
      protocol: TCP
